{% set name = "json-c" %}
{% set version = "0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version.split('-')[0] }}

source:
  url: https://s3.amazonaws.com/json-c_releases/releases/json-c-{{ version }}.tar.gz
  sha256: b8d80a1ddb718b3ba7492916237bbf86609e9709fb007e7f7d4322f02341a4c6
  patches:
    - 00-add-library-inc.patch
    - 01-patch-install-json_object_iterator-h-header-file.patch

build:
  number: 1002
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - cmake  # [win]
    - make
  host:
    - msinttypes  # [win and vc<=9]

test:
  commands:
    - test -f ${PREFIX}/lib/libjson-c.a  # [not win]
    - test -f ${PREFIX}/lib/libjson-c${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_BIN%/json-c.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%/json-c.lib exit 1  # [win]

about:
  home: https://github.com/json-c/json-c/wiki
  license: MIT
  license_file: COPYING
  summary: 'A JSON implementation in C'

extra:
  recipe-maintainers:
    - ocefpaf
    - sodre
    - djsutherland
