{% set version = "0.12.1" %}

package:
  name: json-c
  version: {{ version }}

source:
  fn: json-c-{{ version }}.tar.gz
  url: https://s3.amazonaws.com/json-c_releases/releases/json-c-{{ version }}.tar.gz
  sha256: 2a136451a7932d80b7d197b10441e26e39428d67b1443ec43bbba824705e1123

build:
  number: 0

requirements:
  build:
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - m2-autoconf  # [win]
    - m2-automake1.15  # [win]
    - m2-libtool  # [win]
    - posix  # [win]
    - m2w64-toolchain  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libjson-c.a  # [unix]
    - test -f ${PREFIX}/lib/libjson-c.so  # [linux]
    - test -f ${PREFIX}/lib/libjson-c.dylib  # [osx]
    - conda inspect linkages -p ${PREFIX} json-c  # [linux]

about:
  home: https://github.com/json-c/json-c/wiki
  license: MIT
  license_file: COPYING
  summary: 'A JSON implementation in C.'

extra:
  recipe-maintainers:
    - ocefpaf
